databases:
  - name: kkanakana-db
    databaseName: kkanakana-db
    user: kkanakana
    region: singapore

services:
  - type: web
    name: kkanakana-backend
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kkanakana
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
