databases:
  - name: kkana-kana
    databaseName: kkana-kana
    user: kkana-kana
    region: singapore

services:
  - type: web
    name: kkanaka-kana
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kkana-kana
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
